### PR TITLE
fix: wording, fix #855

### LINKED ISSUE #855: Changer le titre et le texte dans la rubrique "Objectif d'impact à 6 mois" sur la fiche produit
TITRE ACTUEL
Objectif d'impact à 6 mois

REMPLACER PAR
Objectifs à 6 mois

TEXTE ACTUEL
Quel impact chiffré visez-vous ? Qu'est-ce qui vous permettra de dire si votre première phase de construction a été un succès au bout des 6 premiers mois ?

REMPLACER PAR
Objectif d'usage à 6 mois : quel usage chiffré visez-vous ?
Objectif d'impact à 6 mois : quel impact chiffré vous permettra de dire que votre première phase de construction a été un succès ?

Vu avec @Tibo-aplus

### PR DESCRIPTION
**Pull request by revolunet**
fix #855

Capture d’écran 2025-03-14 à 09 52 00

### CODE REVIEW

**Comment by revolunet** [comment]
up, someone needs to "Accept"

File: src/components/StartupForm/StartupForm.tsx [hunk 1]
```diff
@@ -61,9 +61,11 @@ Les problèmes que vous avez identifiés ou vos hypothèses de problèmes ? Qui
 
 Décris ta solution en quelques lignes ? Qui seront les bénéficiaires ?
 
-## Objectifs d'impact à 6 mois
+## Objectifs à 6 mois
 
-Quel impact chiffré visez-vous ? Qu'est-ce qui vous permettra de dire si votre première phase de construction a été un succès au bout des 6 premiers mois ?
+Objectif d'usage à 6 mois : quel usage chiffré visez-vous ?
```
Comment (freesteph) [inline src/components/StartupForm/StartupForm.tsx:66]:
```suggestion
Objectif **d'usage** à 6 mois : quel usage chiffré visez-vous ?
```

File: src/components/StartupForm/StartupForm.tsx [hunk 2]
```diff
@@ -61,9 +61,11 @@ Les problèmes que vous avez identifiés ou vos hypothèses de problèmes ? Qui
...
+
+Objectif d'impact à 6 mois : quel impact chiffré vous permettra de dire que votre première phase de construction a été un succès ?
```
Comment (freesteph) [inline src/components/StartupForm/StartupForm.tsx:68]:
```suggestion
Objectif **d'impact** à 6 mois : quel impact chiffré vous permettra de dire que votre première phase de construction a été un succès ?
```

**Review by freesteph — APPROVED** [review]
